In [2]:
import numpy as np

In [40]:
a = np.array([4,10,12,23,-2,-1,0,0,0,-6,3,-7])

In [ ]:
#1

In [5]:
len(a[a<0])

4

In [ ]:
#2

In [7]:
len(a[a>=0])

8

In [ ]:
#3

In [42]:
len(a[(a>=0) & (a % 2 ==0)])

6

In [ ]:
#4

In [15]:
b=a+3
len(b[b>=0])

10

In [ ]:
#5

In [17]:
b=a**2
b.std()

144.0243035046516

In [ ]:
#6

In [21]:
b=a.mean()
c = a - b
print(c) #array centered
c.mean()

# or : use centered 



[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


0.0

In [ ]:
#7

In [23]:
z_score = (a -  a.mean()) / a.std()
print(z_score) 

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


In [ ]:
#Other stuff

In [24]:
b = np.array([
    [3,4,5],
    [6,7,8],
  
])

In [25]:
#shape of array
np.shape(b)

(2, 3)

In [26]:
#transposing array dem
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [28]:
#reshapes the array using tuple of ints
np.reshape(b, (6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

1.707825127659933

In [37]:
a = np.arange(1,51)
b=np.reshape(a, (10,5))
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
